name: STM32 Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup ARM GCC
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '10.3-2021.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make
        
    - name: Build project
      run: |
        make clean
        make all
        make copy-artifacts
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ github.sha }}
        path: |
          *.bin
          *.hex
          *.elf
        retention-days: 30
        
    - name: Create release on tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.bin
          *.hex
          *.elf
